//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//!
//! To regenerate: `sea-orm-cli generate entity -u "$DATABASE_URL" -o ./src/entities --with-serde both`

pub mod note_edits;
pub mod notes;
